name: russellmorbey-api
services:
- name: api
  source_dir: /
  github:
    repo: russellmorbey/API-web-service  # Update with your actual GitHub username
    branch: main
  run_command: uvicorn multi_project_api:app --host 0.0.0.0 --port 8080 --workers 1 --access-log --log-level info
  instance_count: 1
  instance_size_slug: basic-xxs  # $5/month plan
  dockerfile_path: Dockerfile.production
  
  # Environment variables (set as secrets in DigitalOcean dashboard)
  envs:
  - key: STRAVA_CLIENT_ID
    scope: RUN_TIME
    type: SECRET
  - key: STRAVA_CLIENT_SECRET
    scope: RUN_TIME
    type: SECRET
  - key: STRAVA_ACCESS_TOKEN
    scope: RUN_TIME
    type: SECRET
  - key: STRAVA_REFRESH_TOKEN
    scope: RUN_TIME
    type: SECRET
  - key: STRAVA_EXPIRES_AT
    scope: RUN_TIME
    type: SECRET
  - key: STRAVA_EXPIRES_IN
    scope: RUN_TIME
    type: SECRET
  - key: STRAVA_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: FUNDRAISING_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: JAWG_ACCESS_TOKEN
    scope: RUN_TIME
    type: SECRET
  - key: JUSTGIVING_URL
    scope: RUN_TIME
    type: SECRET
  - key: PORT
    scope: RUN_TIME
    value: "8080"
  - key: ENVIRONMENT
    scope: RUN_TIME
    value: "production"
  - key: DIGITALOCEAN_API_TOKEN
    scope: RUN_TIME
    type: SECRET
  - key: DIGITALOCEAN_APP_ID
    scope: RUN_TIME
    type: SECRET
  
  # Health check configuration
  health_check:
    http_path: /api/strava-integration/health
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  
  # Resource limits (Basic plan)
  instance_count: 1
  instance_size_slug: basic-xxs